### PR TITLE
Determining position of multiple cursors independently

### PR DESCRIPTION
**Pull request by efatsi**
gif

### CODE REVIEW

**Comment by efatsi** [comment]
Wrote a spec for it, not sure how to run specs for the package however.

**Comment by leejarvis** [comment]
Hi Eli, thanks for this.

Unfortunately I don't maintain this package anymore (I need to add a note to that effect to the README). If you'd like to fork this repo and maintain your own version please do, alternatively if you'd like to maintain this version I'm happy to give you full permission.

I haven't used Atom almost since creating this plugin, and don't intend to start in the near future.

Thanks again!

**Comment by efatsi** [comment]
I'd be happy to take over the repo. I use Atom every day and this was one of the first packages I installed. Thanks for all your work on it so far!

**Comment by leejarvis** [comment]
Excellent, thanks. I've added you as a collaborator. Feel free to take full control. Let me know if you need anything from me. 

Cheers!

**Comment by doggan** [comment]
Thanks for this update and your work, guys! This is a great plugin. :sparkles:

**Pull request merged**
